### ISSUE TITLE
RSS feed is missing

### ISSUE THREAD

**Issue by redstrate** [joren485/blog#1]
Hey you have a cool blog :-) I wanted to follow it using my RSS reader, and I tried the alternate-feed link suggested by the Jekyll theme but it doesn't appear to be generated and [Github returns a 404](https://blog.nietaanraken.nl/feed.xml).

It looks like all you have to do is add the Jekyll-feed plugin as suggested by this [post](https://dzhavat.github.io/2020/01/19/adding-an-rss-feed-to-github-pages.html).

**Comment by joren485** [comment]
Thank you for your interest :smile: 

I added [an RSS feed](https://blog.nietaanraken.nl/feed.xml) in da6610e9e448ae6534770a187618bae41a46d840.
